### ISSUE TITLE
Errors not being added to model

### ISSUE THREAD

**Issue by adambedford** [Exelord/ember-custom-actions#18]
If the record fails validation on the server and returns a 422 with JSON-API compliant errors, these errors do not get set on the model. I have `pushToStore` turned on.

Is this expected behavior? Is there a good way to set the model errors manually?

**Comment by Exelord** [comment]
Hey @adambedford :)
Unfortunately this will be not possible :/ You shouldn't add errors from custom actions to the model. These are reserved for the save state.

However, you should look to the #15. There you can find a solution and explanation.
> This PR will allow you to access `serialized errors` from `error` object from your response.

I want to have this merged we I still can't figure out how to tests catch responses with QUnit. If you have any idea and want to speed it up - go ahead and bring us some genius solution :D

**Comment by Exelord** [comment]
#15 currently merged so you can get access to serialized errors by catching an error and invoking `error.serializedErrors` :)

**Comment by glapworth** [comment]
Does `error.serializedErrors` return from a customAction?

**Comment by Exelord** [comment]
Its returned in custom action error. 
eg. `this.model.myCustomAction().catch((error) => error. serializedErrors)`
