### ISSUE TITLE
Could not find module `ember-data/-private/debug` imported from `ember-custom-actions/serializers/rest`

### ISSUE THREAD

**Issue by adambedford** [Exelord/ember-custom-actions#20]
I'm running into an issue where this error is being raised:

```
Could not find module `ember-data/-private/debug` imported from `ember-custom-actions/serializers/rest`
```

I think it relates to https://github.com/emberjs/data/issues/5021 but it still seems like a bug with this library. Looks like a private API is being used, which has been moved in recent versions of Ember Data?

This issue exists at least in Ember Data 2.14.3.

**Comment by Exelord** [comment]
Fixed in #21 :) Thank you for the report!
