### ISSUE TITLE
Cannot use Ember.Object as payload

### ISSUE THREAD

**Issue by medokin** [Exelord/ember-custom-actions#23]
https://github.com/Exelord/ember-custom-actions/blob/master/addon/actions/action.js#L33

Type check allows only `object`, but an ember object is type `instance`. Therefore the payload gets ignored, without any warning or error.

**Comment by Exelord** [comment]
Hmm... Yea I know that it would be awesome to support Ember Object but it can be not so convenient. Ember Objects can have computed propertis which I would have to resolve but I do not know which I should or shoud not. So, basicaly you should always pass `Object` as a param property.

But you are right. It should warn about that. I will definitely add it to my scheduled tasks.

**Comment by medokin** [comment]
I think it's not up to this addon to decide which properties needs to be resolved. 
IMHO It should pass everything the dev puts into it. He knows best what he wants.

**Comment by Exelord** [comment]
> IMHO It should pass everything the dev puts into it.

If you will pass a string it should also work? Really... I don't get your point.

If he knows what he wants please do not bother to fork it and use it as you like. The API of Ember Custom Actions requires to pass an `Object` not an `Ember Object` and it won't change as ember objects contain computed properties which I don't want to resolve on package side.

**Comment by Exelord** [comment]
Added the error messages when payload is not an object in #28
