### ISSUE TITLE
Support for adapters layer

### ISSUE THREAD

**Issue by KillaPL** [Exelord/ember-custom-actions#25]
In my code I forced to send some headers with the custom actions. It ends up being a code like this:

```
const body = this.get("model.foo")
const etag = this.get("model.etag");
const ajaxOptions = {
  headers: {
    "If-Match": version
  }
};

this.get("model").barAction(body, {ajaxOptions})
```

In quite many places.
I believe this code should live in adapter of proper model, and would therefore like to suggest a new feature: adapter integration.

Custom action should look, by default, look for headers in models adapter. So having a code like this in model:

```
import ApplicationModel from "./application-model";
import { modelAction } from "ember-custom-actions";

export default ApplicationModel.extend({
  barAction: modelAction("bar-action"),
});
```

and adapter like this:

```
import ApplicationAdapter from "./application";

export default ApplicationAdapter.extend({
  headersForRequest(params) {
    if(params.requestType === "bar-action") {
      const etag = params.snapshot.attr("etag");
      return {
        "If-Match": etag
      };
    } else {
      return this._super(params);
    }
  },
});
```

It would be enough in actual calling of the action to do:

```
const body = this.get("model.foo")
this.get("model").barAction(body)
```

If this idea is accepted I am more than happy to implement it, it would cleanup my codebase nicely.

I also have other issues of the same nature: ability to specify url in adapter for a custom action, and ability to specify a body in serializer in the similiar manner. I'm happy to create new issues for them when this one is settled, or right away.

EDIT

After some more time spend thinking about it, maybe better approach would be to introduce 3 new methods specific for custom actions: `urlForCustomAction`, `headersForCustomAction` and `methodForCustomAction` ?

Code would look for them in adapter, and if they are there, their result would be used.

**Comment by Exelord** [comment]
Yea, the `urlForCustomAction` and `headersForCustomAction` would be great! It will solve also part of #24 

but indeed there should be:
- `urlForCustomModelActions`
`urlForCustomResourceActions`

or we should make it by meta programming like:
- `urlForMySuperCustomAction`
- `headerForMySuperCustomAction`
if the function will be found we will use it else we will fall back to the current behavior.

What do you think?

**Comment by Exelord** [comment]
And then of course use `adapterOptions` to customize it like @scottwernervt said in #24

**Comment by Exelord** [comment]
```js
  _buildUrl(id) {
    let query = this.get('params');
    let snapshot = this.get('snapshot');
    let modelName = this.get('modelName');
    let requestType = this.get('urlType');

    let customUrlFor = this.get('adapter').get(`urlFor${this.get('urlType').camelize()}`);
    return customUrlFor ? customUrlFor(modelName, id, query, snapshot) : this.get('adapter').buildURL(modelName, id, snapshot, requestType, query);
  },
```

Ok, I think it should looks most likely like this (of course it needs to be refactored)

**Comment by KillaPL** [comment]
I started some work locally already with those ideas. I will prepare a PR with my initial thoughts, and we can start from there : )

**Comment by Exelord** [comment]
As we moved with adapter's support we need to also handle those methods before we will be able to release the integration.

TODO:
- [ ] `generateIdForRecord`
- [ ] `headersForRequest`
- [ ] `methodForRequest`
- [ ] `dataForRequest`

**Comment by Exelord** [comment]
Done. Let's test it out for a few weeks now.
