### ISSUE TITLE
Assertion Failed: You must provide a path for model action!

### ISSUE THREAD

**Issue by adambedford** [Exelord/ember-custom-actions#39]
I'd like to use `ember-custom-actions` to implement a `softDelete()` method on a model that issues a `DELETE` request to the resource endpoint. For example, if the resource is `tasks` and the ID is `2`, the URL would be `api/tasks/2`. 

I've implemented a `modelAction`, however I haven't been able to configure it as I'd expected, and I'm running into the error `Assertion Failed: You must provide a path for model action!` because the `path` is empty ( I don't want the URL to be `api/tasks/2/soft-delete`, for example).

Here's the model config:
```javascript
softDelete: modelAction("", { method: "DELETE" })
```

I'm also observing that the `method` isn't respected, as a `PUT` request is actually being issued when I test the `path` as `/`, for example.

**Comment by Exelord** [comment]
Hey, sure its doable!

You are looking at readme to v3.0.0-beta.0 that's why the `method` doesn't work. In your version it's `type`.

If want to call this url you need to use the latest beta, which integrates adapters support.

Then you have to use `customAction`:
```js
softDelete: modelAction('softDelete', { method: "DELETE" })
```

In your  adapter define a custom URL for it like inthe readme:
```js
import JSONAPIAdapter from 'ember-data/adapters/json-api';
import { AdapterMixin } from 'ember-custom-actions';

export default JSONAPIAdapter.extend(AdapterMixin, {
  urlForCustomAction(modelName, id, snapshot, actionId, queryParams) {
    if (requestType === 'softDelete') {
       return `${this._buildURL(modelName, id)};
    }
    
    return this._super(...arguments);
  }
});
```

**Comment by Exelord** [comment]
But, that's an interesting case to simplify it. I think we should allow on it

**Comment by adambedford** [comment]
Thanks, @Exelord, your example worked perfectly!
