### ISSUE TITLE
Pass payload through serializer?

### ISSUE THREAD

**Issue by adambedford** [Exelord/ember-custom-actions#41]
I have a non-REST endpoint `users/invite` and I'm trying to figure how to use this library to send a payload to that endpoint using JSONAPI format. My Application serializer uses JSONAPISerializer from `ember-custom-actions` already (I'm using this library in a couple other places already).

I'd like `user.invite()` to behave the same as `user.save()` in the sense that the User model is serialized (JSONAPI format) and sent as params to the endpoint.

On my User model, I have the following property:

```es6
invite: resourceAction("invite", { method: "POST" })
```

and in my `invite` action, I'm doing this:

```es6
invite(user) {
  user.invite(user.toJSON()).then(...)
}
```

The problem is that the payload doesn't pass through the ApplicationSerializer. I feel like I'm missing something obvious here!

**Comment by Exelord** [comment]
Yes, if you would like use serializers and adapter you have to use `customAction` instead of `resourceAction`. It should be well documented in the readme. If it's not, give me some hints and I will improve it. :)

**Comment by Exelord** [comment]
Oh, sorry! you want to serialize your payload by the serializer. I think this is not implemented. You need to override `dataForCustomAction` and specify there your own payload serializing correctly a model by yourself, or model's serializer.

**Comment by Exelord** [comment]
You can also try https://emberjs.com/api/ember-data/3.0/classes/DS.Model/methods/serialize?anchor=serialize instead of `toJSON()`

**Comment by Exelord** [comment]
Feel free to reopen if needed

**Comment by bertatbagaar** [comment]
I'm also in favour of using serializers to determine the correct (JSON API) payload. This would be more in line with Ember Data. Adapters take care of the request, serializers take care of the payload.

**Comment by bertatbagaar** [comment]
An additional question kind of related to this:
Is there a better way to access the model's data inside `dataForCustomAction` other than using `store.peekRecord` and `params.modelId`? Feels kind of hacky. For instance `urlForCustomAction` has a snapshot parameter that can be used.
