### ISSUE TITLE
urlForCustomAction not working.

### ISSUE THREAD

**Issue by omairrazam** [Exelord/ember-custom-actions#45]
Hi. your addon is really cool.

I configured it as you explain in your docs. I am using version 2.1.0.

In my adapter, I am using some customised url but it is not taking affect. I am not sure why.
This is the url that its make api/v1/users/resetPassword, when I just want api/v1/resetPassword

This is my adapter code. It is already inheriting RESTAdapter.

    import ApplicationAdapter from './application'; 

    import { AdapterMixin } from 'ember-custom-actions';

    export default ApplicationAdapter.extend(AdapterMixin,{

    urlForCustomAction(modelName, id, snapshot, actionId, queryParams) {

    return 'https://domain.com/resetPassword';

    }

    });

Any help will be really appreciated.

Thanks in advance.

**Comment by Exelord** [comment]
What is your action definition? Adapter integration works only with `customAction` not `modelAction` and `resourceAction`

**Comment by omairrazam** [comment]
Hi, thanks for looking into the issue.
I am using resourceAction. In the docs there is no mention of customAction. Secondly I tried customAction and it threw unknown error etc.

**Comment by Exelord** [comment]
There is. Take a look at customAction section. First paragraph. All the integrations are subheaders of this section. I will improve the docs.

customAction has a little different api, did you adjust it? If taht helps you can take a look at dummy app in the code it's using it.

**Comment by omairrazam** [comment]
I tried that but it didn't work, may be I made some mistake. I will check again soon.
