### ISSUE TITLE
[Feature request] Make it possible to add an extra 'callback' function to custom actions

### ISSUE THREAD

**Issue by NindroidX** [Exelord/ember-custom-actions#46]
I think it would be nice if you could pass extra 'callback' functions to the modelAction function.

This makes it possible to optimistically change the state of the model to what is the expected result from the server which improves usability.

What it could look like:
```
export default Model.extend({
  isFavorited: attr('boolean'),

  favorite: modelAction('favorite', {}, function () {
    this.set('isFavorited', true);
  }),
});
```

At the moment this is possible by writing a wrapper function, which calls the custom action, but I think it would be an improvement if this was included in this addon.

Let me know what you think!

**Comment by NindroidX** [comment]
It should probably be integrated differently, the function in the code example might be confused for a response handler.

Maybe the function should be passed as a property on the options object?

**Comment by Exelord** [comment]
You shouldn't change model state during the adapter request. This is not an `action` form the ember meaning. If you need some custom behavior just use:
```js
export default Model.extend({
  isFavorited: attr('boolean'),

  markFavorite: modelAction('favorite'),

  markAsFavorite() {
    this.set('isFavorited', true);
    return this.markFavorite();
  },
});
```

naming is an example.

**Comment by NindroidX** [comment]
Yes, that is how I do it now. It would have been nice to not have to wrap it though, but fair enough.
