### ISSUE TITLE
Warning: cjs already defined

### ISSUE THREAD

**Issue by xtagon** [Exelord/ember-custom-actions#54]
The following warning shows up when my app builds:

>WARNING: Addon "ember-custom-actions" is defining a transform name: cjs that is already being defined. Using transform from addon: "ember-custom-actions".

Any idea what this means?

I'm using Ember 2.18 and ember-custom-actions 3.0.0.

Thanks

**Comment by Exelord** [comment]
It's cjs issue :) Everything is ok. They should fix it soon.
