### ISSUE TITLE
Pass the `model` to `dataForCustomAction` within `params` for enabling serialization

### ISSUE THREAD

**Issue by feanor07** [Exelord/ember-custom-actions#59]
There was a relevant comment regarding this one at https://github.com/Exelord/ember-custom-actions/issues/41#issuecomment-406323411

I think it would be helpful to pass the `model` itself in addition to `modelId` to `dataForCustomAction`; because it is very common case to call `model.serialize()` in order to send the object itself as the payload just  like as if `model.save()` is called.

**Comment by feanor07** [comment]
As of now one needs to inject the `store` to relevant adapter and implement `dataForCustomAction` as follows:

```
dataForCustomAction(params) {
        return this.store.peekRecord('model_name', params.modelId).serialize()
}
```

it would be nicer to have this like
```
dataForCustomAction(params) {
        return params.model.serialize()
}
```

**Comment by feanor07** [comment]
we can close this peacefully after the merge! thx!

**Comment by feanor07** [comment]
@Exelord can we take a release with this commit included anytime soon? it is kind of urgent for us :(

**Comment by adambedford** [comment]
@feanor07 Do you have a good way of passing the model in the payload of all `modelAction`s as well?
