### ISSUE TITLE
Update lodash.merge version for fixing vulnerability

### ISSUE THREAD

**Issue by sinankeskin** [Exelord/ember-custom-actions#63]
There is a vulnerability in [lodash.merge](https://www.npmjs.com/advisories/1066) package. Plase update your lodash.merge dependency version to 4.6.2.

Dependabot [already did](https://github.com/Exelord/ember-custom-actions/commit/fa509a8ab6106624b89363d23eb2895eb6793f64) that for you. You can simple release a new npm version for your package.

Thank you.

**Comment by Exelord** [comment]
Published 3.3.0. Thanks
