### ISSUE TITLE
Way to use in form of decorator!

### ISSUE THREAD

**Issue by aklkv** [Exelord/ember-custom-actions#66]
I am trying to upgrade project to use classes based models. I was wondering if there is a way to use this addon in form of decorator?

**Comment by Exelord** [comment]
There isn't now, but it's very easy to make it :)

**Comment by kjarri** [comment]
I got around this by defining the custom action in a constructor on the model. 

`constructor() {
    super(...arguments);
    this.summaryAction = customAction('summary', {
      method: 'GET',
      pushToStore: false,
      responseType: 'object'
    });
  }`

**Comment by Exelord** [comment]
you can do the same with class fields :) 

```js
class {
  summaryAction = customAction('summary', {
      method: 'GET',
      pushToStore: false,
      responseType: 'object'
    });
}
```

**Comment by kjarri** [comment]
oh, right - thanks!

**Comment by sandstrom** [comment]
@aklkv Can this issue be closed?

https://github.com/Exelord/ember-custom-actions/issues/66#issuecomment-628688195 seems to work for me atleast
